### ISSUE TITLE
pigpio npm module has a dependency to pigpio C library

### ISSUE THREAD

**Issue by hegelstad** [fivdi/pi-io#2]
Please add to the readme that the pigpio dependency needs the pigpio C library installed.

**Comment by fivdi** [comment]
Good idea. Thank you for the suggestion.

**Comment by hegelstad** [comment]
@fivdi thanks for following up.

Gotta be honest, you've created a brilliant lib that doesn't suffer the strange requirements that raspi-io has, like permission - and rebooting before running - requirements!

I used this for my hackathon project on a BalenaCloud provisioned OS, worked flawlessly, plug and play.

**Comment by fivdi** [comment]
Fixed with b2f4ac75b602a1014d5d44bb732ddad4fbc39597
